name: palhetas
description: Palhetas na Foz

publish_to: 'none'

version: 1.8.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  adaptive_theme: ^3.6.0
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  introduction_screen: ^3.1.12
  lottie: ^3.1.0
  path_provider: ^2.1.2
  connectivity_plus: ^2.3.8
  webfeed_revised: ^0.7.2
  http: ^1.2.1
  flutter_widget_from_html: ^0.14.11
  uuid: ^4.3.3
  flutter_svg: ^2.0.10+1
  share_plus: ^7.2.2
  icons_launcher: ^2.1.7
  fast_cached_network_image: ^1.2.8
  fluttertoast: ^8.2.5
  url_launcher: ^6.2.5
  html: ^0.15.4
  download: ^1.0.0
  weather_pack: ^1.1.0
  flutter_tts: ^4.0.2
  html_parser_plus: ^0.1.4
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  background_fetch: ^1.3.4
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^17.1.2
  logger: ^2.3.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # Assets
  assets:

    # Environment Variables
    - .env

    # Animations
    - assets/anim/
